version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookit
      POSTGRES_PASSWORD: bookitpass
      POSTGRES_DB: bookitnow_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U bookit"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - JWT_SECRET
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:4000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["/bin/sh","-c","/usr/src/app/entrypoint-prod.sh node dist/index.js"]

volumes:
  pgdata:
    name: bookitnow_pgdata
