name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend
          tags: |
            type=sha,format=long
            type=raw,value=staging-latest

  deploy-staging:
    needs: prepare
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://api-staging.bookitnow.com  # Replace with your staging domain
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .github/deployment/task-definition.json
          service: bookitnow-backend-staging
          cluster: bookitnow-staging
          wait-for-service-stability: true
          container-name: backend
          image: ${{ needs.prepare.outputs.image_tag }}